<?xml version="1.0"?>
<definitions xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd" xmlns:wsp="http://www.w3.org/ns/ws-policy" xmlns:wsp1_2="http://schemas.xmlsoap.org/ws/2004/09/policy" xmlns:wsam="http://www.w3.org/2007/05/addressing/metadata" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://helloservice.tutorial.jakarta/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="http://schemas.xmlsoap.org/wsdl/" targetNamespace="http://helloservice.tutorial.jakarta/" name="bookWeb">
<types>
<xsd:schema>
<xsd:import namespace="http://helloservice.tutorial.jakarta/" schemaLocation="http://binta:8080/helloservice-war/bookWeb?xsd=1"/>
</xsd:schema>
</types>
<message name="getBookById">
<part name="parameters" element="tns:getBookById"/>
</message>
<message name="getBookByIdResponse">
<part name="parameters" element="tns:getBookByIdResponse"/>
</message>
<portType name="bookWs">
<operation name="getBookById">
<input wsam:Action="http://helloservice.tutorial.jakarta/bookWs/getBookByIdRequest" message="tns:getBookById"/>
<output wsam:Action="http://helloservice.tutorial.jakarta/bookWs/getBookByIdResponse" message="tns:getBookByIdResponse"/>
</operation>
</portType>
<binding name="bookWsPortBinding" type="tns:bookWs">
<soap:binding transport="http://schemas.xmlsoap.org/soap/http" style="document"/>
<operation name="getBookById">
<soap:operation soapAction=""/>
<input>
<soap:body use="literal"/>
</input>
<output>
<soap:body use="literal"/>
</output>
</operation>
</binding>
<service name="bookWeb">
<port name="bookWsPort" binding="tns:bookWsPortBinding">
<soap:address location="http://binta:8080/helloservice-war/bookWeb"/>
</port>
</service>
</definitions>