<?xml version="1.0"?>
<definitions xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd" xmlns:wsp="http://www.w3.org/ns/ws-policy" xmlns:wsp1_2="http://schemas.xmlsoap.org/ws/2004/09/policy" xmlns:wsam="http://www.w3.org/2007/05/addressing/metadata" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://helloservice.tutorial.jakarta/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="http://schemas.xmlsoap.org/wsdl/" targetNamespace="http://helloservice.tutorial.jakarta/" name="HelloService">
<types>
<xsd:schema>
<xsd:import namespace="http://helloservice.tutorial.jakarta/" schemaLocation="http://localhost:8080/helloservice-war/HelloService?xsd=1"/>
</xsd:schema>
</types>
<message name="getClient">
<part name="parameters" element="tns:getClient"/>
</message>
<message name="getClientResponse">
<part name="parameters" element="tns:getClientResponse"/>
</message>
<message name="sayHello">
<part name="parameters" element="tns:sayHello"/>
</message>
<message name="sayHelloResponse">
<part name="parameters" element="tns:sayHelloResponse"/>
</message>
<portType name="Hello">
<operation name="getClient">
<input wsam:Action="http://helloservice.tutorial.jakarta/Hello/getClientRequest" message="tns:getClient"/>
<output wsam:Action="http://helloservice.tutorial.jakarta/Hello/getClientResponse" message="tns:getClientResponse"/>
</operation>
<operation name="sayHello">
<input wsam:Action="http://helloservice.tutorial.jakarta/Hello/sayHelloRequest" message="tns:sayHello"/>
<output wsam:Action="http://helloservice.tutorial.jakarta/Hello/sayHelloResponse" message="tns:sayHelloResponse"/>
</operation>
</portType>
<binding name="HelloPortBinding" type="tns:Hello">
<soap:binding transport="http://schemas.xmlsoap.org/soap/http" style="document"/>
<operation name="getClient">
<soap:operation soapAction=""/>
<input>
<soap:body use="literal"/>
</input>
<output>
<soap:body use="literal"/>
</output>
</operation>
<operation name="sayHello">
<soap:operation soapAction=""/>
<input>
<soap:body use="literal"/>
</input>
<output>
<soap:body use="literal"/>
</output>
</operation>
</binding>
<service name="HelloService">
<port name="HelloPort" binding="tns:HelloPortBinding">
<soap:address location="http://localhost:8080/helloservice-war/HelloService"/>
</port>
</service>
</definitions>